services:
  - type: web
    name: celex-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: YUGABYTE_JDBC_URL
        sync: false
      - key: YUGABYTE_DB_USER
        sync: false
      - key: YUGABYTE_DB_PASSWORD
        sync: false
